---
- name: add php5 repo
  apt_repository:
    repo: 'ppa:ondrej/apache2'

- name: Update apt
  apt: update_cache=yes

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - apache2

- name: Enabled mod_rewrite
  apache2_module: name=rewrite state=present

- name: Disable default configuration
  file: dest=/etc/apache2/sites-enabled/000-default state=absent
