---
- name: "Configure/Confirm Directory Structure"
  file: path="{{ mountpath }}" state=directory owner=root group=root mode="{{ permissions }}" recurse="{{ recurse }}"

- name: "Create Filesystem for Disk"
  filesystem:
    fstype: ext4
    dev: "{{ physicalmount }}"

- name: "Mount Disk"
  mount:
    path: "{{ mountpath }}"
    src: "{{ physicalmount }}"
    fstype: ext4
    state: mounted
