---
- hosts: tag_Role_nginx

  tasks:
  - name: Ensure directory structure exists
    file:
      path: /app
      state: directory
      mode: 0755
      owner: www-data
      group: www-data

  - name: Git clone Flask Directory
    git:
      repo: git@github.com:adamlash/aws-documenter.git
      dest: /app/awsdocumenter
      accept_hostkey: yes
    become: yes
