---
- hosts: tag_Role_nginx
  roles:
    - jdauphant.nginx

  vars:
    nginx_sites:
      awsdocumenter:
        - listen 80
        - server_name awsdocumenter.co.nz
        - location / {
          include proxy_params;
          proxy_pass http://unix:/app/awsdocumenter/awsdocumenter.sock;
          }
