---
- name: Update apt
  apt: update_cache=yes

- name: Install apache2 http server
  apt:
    name: "{{ item }}"
    state: present
  with_items: apache_packages

- name: Enabled mod_rewrite
  apache2_module: name=rewrite state=present

- name: Disable default configuration
file: dest=/etc/apache2/sites-enabled/000-default state=absent
