- name: Create Groups
  group:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ group_list }}"

- name: Remove Groups
  group:
    name: "{{ item.name }}"
  with_items:
    - "{{ group_removal }}"

- name: Add admin groups to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ item.name }}"
    line: "%{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  when: item.admingroup == "yes"
  with_items:
    - "{{ group_list }}"

- name: Setup Users
  user:
    name: "{{ item.username }}"
    state: "{{ item.state | default('present') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    group: "{{ item.group | default('infra_admins') }}"
    remove: yes
  when: item.username is defined
  with_items:
    - "{{ admin_list }}"

- name: Add SSH-keys to users
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ admin_list }}"
    - keys.active
    - flags:
      skip_missing: True
  when: item.0.state != "absent"

- name: Remove old SSH-keys from users
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    state: absent
  with_subelements:
    - "{{ admin_list }}"
    - keys.disabled
    - flags:
      skip_missing: True
  when: item.0.state != "absent"
