- name: Check if Packer is Installed
  stat: path=/usr/local/bin/packer
  register: packer_installed

- name: Download Packer
  get_url:
    url: https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
    dest: /tmp/packer.zip
  when: packer_installed.exists == False

- name: Install Packer
  unarchive:
    src: /tmp/packer.zip
    dest: /user/local/bin
  when: packer_installed.exists == False
