- name: Launch Cloudformation Stack
  cloudformation:
    stack_name: "{{ cfn_stackname }}"
    state: "present"
    region: "us-west-2"
    disable_rollback: true
    template_url: "https://s3-us-west-2.amazonaws.com/adamlashhaws-cloudformation-templates/origin/master/ec2/ec2-standalone.yaml"
    template_parameters:
      ParventVPCStack: al-vpc-services-1
      InstanceType: "{{ cfn_instancetype }}"
      AMIID: "{{ cfn_ami }}"
      Name: "{{ cfn_instancename }}"
      SubnetName: "{{ cfn_subnet }}"
      KeyName: "{{ cfn_keyname | default('') }}"
      SSHAccessGroup: "{{ cfn_sshaccessgroup | default('') }}"
      SSHAccessCIDR: "{{ cfn_sshaccesscidr | default('') }}"
      DataDisk: "{{ cfn_datadisk | default('') }}"
      ParentAWXStack: "{{ cfn_awxstack | default('') }}"
      AWXorSSM: "{{ cfn_ssmorawxmanage }}"
    tags:
      CreatedBy: "AWX Template - Standalone EC2 Instance Creation"
      Role: "{{ cfn_roletag }}"
