---
- name: "Set the instance ID for the play"
  shell: ec2metadata --instance-id
  register: instance_id

- name: "Show Instance ID"
  debug:
    msg: "My Instance ID is: {{ instance_id.stdout }}"

- name: "Change Hostname to Instance-ID"
  hostname:
    name: "{{ instance_id.stdout }}"

- name: "set timezone"
  hosts: all
  timezone:
    name: "{{ timezone }}"

- name: Install generic packages
  apt: name={{ item }} state=present
  with_items:
    - git
    - software-properties-common
